# vi:syntax=yaml
name: Build Image and Push to ECR search
on:
  push:
    branches:
      - main-arm64
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          platforms: linux/arm64
      - uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e
        with:
          install: true
          version: latest
      - uses: glg-public/build-and-deploy-ecr@main
        with:
          ecr_uri: ${{secrets.SEARCH_ECR_URI}}
          access_key_id: ${{secrets.SEARCH_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.SEARCH_ECR_AWS_SECRET_ACCESS_KEY}}
          dockerfile: solr_docker/Dockerfile
          healthcheck: ''
          platform: linux/arm64
