# vi:syntax=yaml
name: Build Image and Push to ECR glgapp
on:
  push:
    # You can set these branches to any that you want to build and push images from
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: glg-public/build-and-deploy-ecr@main
        with:
          ecr_uri: ${{secrets.CONFERENCE_PLATFORM_ECR_URI}}
          access_key_id: ${{secrets.CONFERENCE_PLATFORM_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.CONFERENCE_PLATFORM_ECR_AWS_SECRET_ACCESS_KEY}}
