# vi:syntax=yaml
name: Build Image and Push to ECR
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-glgapp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: glg-public/build-and-deploy-ecr@main
        with:
          ecr_uri: ${{secrets.GLGAPP_ECR_URI}}
          access_key_id: ${{secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY}}
          healthcheck: ""
