name: Build Image and Push to ECR
on:
  push:
    # You can set these branches to any that you want to build and push images from
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checks out the code from this repo
      - uses: actions/checkout@v2

      # Builds a docker image from ./dockerfile, and pushes it to our ECR repository
      - uses: glg-public/build-and-deploy-ecr@main
        with:
          access_key_id: ${{ secrets.PROTOTYPE_ECR_AWS_ACCESS_KEY_ID }}
          ecr_uri: ${{ secrets.PROTOTYPE_ECR_URI }}
          github_ssh_key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          healthcheck: ""
          secret_access_key: ${{ secrets.PROTOTYPE_ECR_AWS_SECRET_ACCESS_KEY }}
          multipass: |
            aws://${{ secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID }}:${{ secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY }}@${{ secrets.GLGAPP_ECR_URI }}
            aws://${{ secrets.INSIGHTS_ECR_AWS_ACCESS_KEY_ID }}:${{ secrets.INSIGHTS_ECR_AWS_SECRET_ACCESS_KEY }}@${{ secrets.INSIGHTS_ECR_URI }}
            aws://${{ secrets.GDS_REVERSE_PROXY_VAULT_ECR_AWS_ACCESS_KEY_ID }}:${{ secrets.GDS_REVERSE_PROXY_VAULT_ECR_AWS_SECRET_ACCESS_KEY }}@${{ secrets.GDS_REVERSE_PROXY_VAULT_ECR_URI }}
