name: Build Image and Push to ECR
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - name: Build A Docker Image and Push to AWS ECR
        run: |
          BRANCH=$(echo ${{github.ref}} | cut -f3 -d'/')
          CONTAINER_IMAGE="${{secrets.GLGAPP_ECR_URI}}/github/${{github.repository}}/${BRANCH}"
          CONTAINER_IMAGE_SHA="${CONTAINER_IMAGE}:${{github.sha}}"
          CONTAINER_IMAGE_LATEST="${CONTAINER_IMAGE}:latest"
          AWS_REGION=$(echo ${{secrets.GLGAPP_ECR_URI}} | cut -f4 -d'.')

          AWS_ACCESS_KEY_ID="${{secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID}}" \
          AWS_SECRET_ACCESS_KEY="${{secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY}}" \
            aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{secrets.GLGAPP_ECR_URI}}

          docker build -t $CONTAINER_IMAGE_SHA -t $CONTAINER_IMAGE_LATEST .
          docker push $CONTAINER_IMAGE_SHA
          docker push $CONTAINER_IMAGE_LATEST
